/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class DynamicChallenge {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected DynamicChallenge(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(DynamicChallenge obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_DynamicChallenge(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setChallenge(String value) {
		ovpncliJNI.DynamicChallenge_challenge_set(swigCPtr, this, value);
	}

	public String getChallenge() {
		return ovpncliJNI.DynamicChallenge_challenge_get(swigCPtr, this);
	}

	public void setEcho(boolean value) {
		ovpncliJNI.DynamicChallenge_echo_set(swigCPtr, this, value);
	}

	public boolean getEcho() {
		return ovpncliJNI.DynamicChallenge_echo_get(swigCPtr, this);
	}

	public void setResponseRequired(boolean value) {
		ovpncliJNI.DynamicChallenge_responseRequired_set(swigCPtr, this, value);
	}

	public boolean getResponseRequired() {
		return ovpncliJNI.DynamicChallenge_responseRequired_get(swigCPtr, this);
	}

	public void setStateID(String value) {
		ovpncliJNI.DynamicChallenge_stateID_set(swigCPtr, this, value);
	}

	public String getStateID() {
		return ovpncliJNI.DynamicChallenge_stateID_get(swigCPtr, this);
	}

	public DynamicChallenge() {
		this(ovpncliJNI.new_DynamicChallenge(), true);
	}

}
