/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class Event {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected Event(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Event obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_Event(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setError(boolean value) {
		ovpncliJNI.Event_error_set(swigCPtr, this, value);
	}

	public boolean getError() {
		return ovpncliJNI.Event_error_get(swigCPtr, this);
	}

	public void setFatal(boolean value) {
		ovpncliJNI.Event_fatal_set(swigCPtr, this, value);
	}

	public boolean getFatal() {
		return ovpncliJNI.Event_fatal_get(swigCPtr, this);
	}

	public void setName(String value) {
		ovpncliJNI.Event_name_set(swigCPtr, this, value);
	}

	public String getName() {
		return ovpncliJNI.Event_name_get(swigCPtr, this);
	}

	public void setInfo(String value) {
		ovpncliJNI.Event_info_set(swigCPtr, this, value);
	}

	public String getInfo() {
		return ovpncliJNI.Event_info_get(swigCPtr, this);
	}

	public Event() {
		this(ovpncliJNI.new_Event(), true);
	}

}
