/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class ExternalPKICertRequest extends ExternalPKIRequestBase {
	private transient long swigCPtr;

	protected ExternalPKICertRequest(long cPtr, boolean cMemoryOwn) {
		super(ovpncliJNI.ExternalPKICertRequest_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(ExternalPKICertRequest obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_ExternalPKICertRequest(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public void setCert(String value) {
		ovpncliJNI.ExternalPKICertRequest_cert_set(swigCPtr, this, value);
	}

	public String getCert() {
		return ovpncliJNI.ExternalPKICertRequest_cert_get(swigCPtr, this);
	}

	public void setSupportingChain(String value) {
		ovpncliJNI.ExternalPKICertRequest_supportingChain_set(swigCPtr, this, value);
	}

	public String getSupportingChain() {
		return ovpncliJNI.ExternalPKICertRequest_supportingChain_get(swigCPtr, this);
	}

	public ExternalPKICertRequest() {
		this(ovpncliJNI.new_ExternalPKICertRequest(), true);
	}

}
