/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class ExternalPKIRequestBase {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected ExternalPKIRequestBase(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(ExternalPKIRequestBase obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_ExternalPKIRequestBase(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setError(boolean value) {
		ovpncliJNI.ExternalPKIRequestBase_error_set(swigCPtr, this, value);
	}

	public boolean getError() {
		return ovpncliJNI.ExternalPKIRequestBase_error_get(swigCPtr, this);
	}

	public void setErrorText(String value) {
		ovpncliJNI.ExternalPKIRequestBase_errorText_set(swigCPtr, this, value);
	}

	public String getErrorText() {
		return ovpncliJNI.ExternalPKIRequestBase_errorText_get(swigCPtr, this);
	}

	public void setInvalidAlias(boolean value) {
		ovpncliJNI.ExternalPKIRequestBase_invalidAlias_set(swigCPtr, this, value);
	}

	public boolean getInvalidAlias() {
		return ovpncliJNI.ExternalPKIRequestBase_invalidAlias_get(swigCPtr, this);
	}

	public void setAlias(String value) {
		ovpncliJNI.ExternalPKIRequestBase_alias_set(swigCPtr, this, value);
	}

	public String getAlias() {
		return ovpncliJNI.ExternalPKIRequestBase_alias_get(swigCPtr, this);
	}

	public ExternalPKIRequestBase() {
		this(ovpncliJNI.new_ExternalPKIRequestBase(), true);
	}

}
