/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class InterfaceStats {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected InterfaceStats(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(InterfaceStats obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_InterfaceStats(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setBytesIn(long value) {
		ovpncliJNI.InterfaceStats_bytesIn_set(swigCPtr, this, value);
	}

	public long getBytesIn() {
		return ovpncliJNI.InterfaceStats_bytesIn_get(swigCPtr, this);
	}

	public void setPacketsIn(long value) {
		ovpncliJNI.InterfaceStats_packetsIn_set(swigCPtr, this, value);
	}

	public long getPacketsIn() {
		return ovpncliJNI.InterfaceStats_packetsIn_get(swigCPtr, this);
	}

	public void setErrorsIn(long value) {
		ovpncliJNI.InterfaceStats_errorsIn_set(swigCPtr, this, value);
	}

	public long getErrorsIn() {
		return ovpncliJNI.InterfaceStats_errorsIn_get(swigCPtr, this);
	}

	public void setBytesOut(long value) {
		ovpncliJNI.InterfaceStats_bytesOut_set(swigCPtr, this, value);
	}

	public long getBytesOut() {
		return ovpncliJNI.InterfaceStats_bytesOut_get(swigCPtr, this);
	}

	public void setPacketsOut(long value) {
		ovpncliJNI.InterfaceStats_packetsOut_set(swigCPtr, this, value);
	}

	public long getPacketsOut() {
		return ovpncliJNI.InterfaceStats_packetsOut_get(swigCPtr, this);
	}

	public void setErrorsOut(long value) {
		ovpncliJNI.InterfaceStats_errorsOut_set(swigCPtr, this, value);
	}

	public long getErrorsOut() {
		return ovpncliJNI.InterfaceStats_errorsOut_get(swigCPtr, this);
	}

	public InterfaceStats() {
		this(ovpncliJNI.new_InterfaceStats(), true);
	}

}
