/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class KeyValue {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected KeyValue(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(KeyValue obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_KeyValue(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public KeyValue() {
		this(ovpncliJNI.new_KeyValue__SWIG_0(), true);
	}

	public KeyValue(String key_arg, String value_arg) {
		this(ovpncliJNI.new_KeyValue__SWIG_1(key_arg, value_arg), true);
	}

	public void setKey(String value) {
		ovpncliJNI.KeyValue_key_set(swigCPtr, this, value);
	}

	public String getKey() {
		return ovpncliJNI.KeyValue_key_get(swigCPtr, this);
	}

	public void setValue(String value) {
		ovpncliJNI.KeyValue_value_set(swigCPtr, this, value);
	}

	public String getValue() {
		return ovpncliJNI.KeyValue_value_get(swigCPtr, this);
	}

}
