/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class LLVector {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected LLVector(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(LLVector obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_LLVector(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public LLVector() {
		this(ovpncliJNI.new_LLVector__SWIG_0(), true);
	}

	public LLVector(long n) {
		this(ovpncliJNI.new_LLVector__SWIG_1(n), true);
	}

	public long size() {
		return ovpncliJNI.LLVector_size(swigCPtr, this);
	}

	public long capacity() {
		return ovpncliJNI.LLVector_capacity(swigCPtr, this);
	}

	public void reserve(long n) {
		ovpncliJNI.LLVector_reserve(swigCPtr, this, n);
	}

	public boolean isEmpty() {
		return ovpncliJNI.LLVector_isEmpty(swigCPtr, this);
	}

	public void clear() {
		ovpncliJNI.LLVector_clear(swigCPtr, this);
	}

	public void add(long x) {
		ovpncliJNI.LLVector_add(swigCPtr, this, x);
	}

	public long get(int i) {
		return ovpncliJNI.LLVector_get(swigCPtr, this, i);
	}

	public void set(int i, long val) {
		ovpncliJNI.LLVector_set(swigCPtr, this, i, val);
	}

}
