/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class LogInfo {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected LogInfo(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(LogInfo obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_LogInfo(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public LogInfo() {
		this(ovpncliJNI.new_LogInfo__SWIG_0(), true);
	}

	public LogInfo(String str) {
		this(ovpncliJNI.new_LogInfo__SWIG_1(str), true);
	}

	public void setText(String value) {
		ovpncliJNI.LogInfo_text_set(swigCPtr, this, value);
	}

	public String getText() {
		return ovpncliJNI.LogInfo_text_get(swigCPtr, this);
	}

}
