/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class MergeConfig {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected MergeConfig(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(MergeConfig obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_MergeConfig(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setStatus(String value) {
		ovpncliJNI.MergeConfig_status_set(swigCPtr, this, value);
	}

	public String getStatus() {
		return ovpncliJNI.MergeConfig_status_get(swigCPtr, this);
	}

	public void setErrorText(String value) {
		ovpncliJNI.MergeConfig_errorText_set(swigCPtr, this, value);
	}

	public String getErrorText() {
		return ovpncliJNI.MergeConfig_errorText_get(swigCPtr, this);
	}

	public void setBasename(String value) {
		ovpncliJNI.MergeConfig_basename_set(swigCPtr, this, value);
	}

	public String getBasename() {
		return ovpncliJNI.MergeConfig_basename_get(swigCPtr, this);
	}

	public void setProfileContent(String value) {
		ovpncliJNI.MergeConfig_profileContent_set(swigCPtr, this, value);
	}

	public String getProfileContent() {
		return ovpncliJNI.MergeConfig_profileContent_get(swigCPtr, this);
	}

	public void setRefPathList(SWIGTYPE_p_std__vectorT_std__string_t value) {
		ovpncliJNI.MergeConfig_refPathList_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
	}

	public SWIGTYPE_p_std__vectorT_std__string_t getRefPathList() {
		long cPtr = ovpncliJNI.MergeConfig_refPathList_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
	}

	public MergeConfig() {
		this(ovpncliJNI.new_MergeConfig(), true);
	}

}
