/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class ServerEntry {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected ServerEntry(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(ServerEntry obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_ServerEntry(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setServer(String value) {
		ovpncliJNI.ServerEntry_server_set(swigCPtr, this, value);
	}

	public String getServer() {
		return ovpncliJNI.ServerEntry_server_get(swigCPtr, this);
	}

	public void setFriendlyName(String value) {
		ovpncliJNI.ServerEntry_friendlyName_set(swigCPtr, this, value);
	}

	public String getFriendlyName() {
		return ovpncliJNI.ServerEntry_friendlyName_get(swigCPtr, this);
	}

	public ServerEntry() {
		this(ovpncliJNI.new_ServerEntry(), true);
	}

}
