/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class SessionToken {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected SessionToken(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(SessionToken obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_SessionToken(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setUsername(String value) {
		ovpncliJNI.SessionToken_username_set(swigCPtr, this, value);
	}

	public String getUsername() {
		return ovpncliJNI.SessionToken_username_get(swigCPtr, this);
	}

	public void setSession_id(String value) {
		ovpncliJNI.SessionToken_session_id_set(swigCPtr, this, value);
	}

	public String getSession_id() {
		return ovpncliJNI.SessionToken_session_id_get(swigCPtr, this);
	}

	public SessionToken() {
		this(ovpncliJNI.new_SessionToken(), true);
	}

}
