/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class Status {
	private transient long swigCPtr;
	protected transient boolean swigCMemOwn;

	protected Status(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Status obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				ovpncliJNI.delete_Status(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setError(boolean value) {
		ovpncliJNI.Status_error_set(swigCPtr, this, value);
	}

	public boolean getError() {
		return ovpncliJNI.Status_error_get(swigCPtr, this);
	}

	public void setStatus(String value) {
		ovpncliJNI.Status_status_set(swigCPtr, this, value);
	}

	public String getStatus() {
		return ovpncliJNI.Status_status_get(swigCPtr, this);
	}

	public void setMessage(String value) {
		ovpncliJNI.Status_message_set(swigCPtr, this, value);
	}

	public String getMessage() {
		return ovpncliJNI.Status_message_get(swigCPtr, this);
	}

	public Status() {
		this(ovpncliJNI.new_Status(), true);
	}

}
