/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.openvpn.ovpn3;

public class SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t {
	private transient long swigCPtr;

	protected SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t(long cPtr, boolean futureUse) {
		swigCPtr = cPtr;
	}

	protected SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t() {
		swigCPtr = 0;
	}

	protected static long getCPtr(SWIGTYPE_p_std__vectorT_openvpn__ClientAPI__KeyValue_t obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}
}
